DROP TABLE F16_1_BRANCH_EMPLOYEE_ASSOCIATION;


DROP TABLE F16_1_SERVICE_EVENT_ASSOCIATION;

DROP TABLE F16_1_EVENTS;

DROP TABLE F16_1_TYPE_OF_EVENTS;

DROP TABLE F16_1_CLIENTS;

DROP TABLE F16_1_OPERATIONS_COST;

DROP TABLE F16_1_BRANCHES;

DROP TABLE F16_1_EMPLOYEES;

DROP TABLE F16_1_SERVICES;

COMMIT;