-- QUERY FOR UPDATING THE EVENT LOCATION--

UPDATE F16_1_EVENTS 
SET LOC_NAME='DBU CHURCH' 
WHERE EVENT_NAME LIKE'%JOHN AND JANE%';


-- QUERY SALARY HIKES OF 125% FOR EVERY EMPLOYEE--

UPDATE F16_1_EMPLOYEES 
SET SALARY_PER_HOUR = SALARY_PER_HOUR*1.25;

-- QUERY DELETING A TYPE OF EVENT--

DELETE FROM F16_1_TYPE_OF_EVENTS 
WHERE TYPE_NAME LIKE '%FASHION SHOW%'

-- QUERY UPDATING BRANCH NAME --

UPDATE F16_1_BRANCHES 
SET BRANCH_NAME='DALLAS STARS' 
WHERE BRANCH_NAME LIKE '%DALLAS%'

-- QUERY UPDATE PHONE NUMBER OF AN EMPLOYEE--

UPDATE F16_1_EMPLOYEES 
SET Telephone_Number='7894561235' 
WHERE EMPLOYEE_ID=3;

-- QUERY TO UPDATE THE BRANCH OF GIVEN EVENT--
UPDATE F16_1_EVENTS
SET BRANCH_ID=3
WHERE EVENT_ID=3;

